### ISSUE TITLE
Unable to download libstorj for platform: win32 and arch: x64

### ISSUE THREAD

**Issue by dittops** [Storj/node-libstorj#57]
I'm trying to install on my windows 10 machine. But I'm getting this error. Can anyone please help here?

> storj@5.0.0 preinstall C:\xampp\htdocs\GenaroEden_Client\node_modules\.staging\storj-04cb61e8
> node ./download.js

Unable to download libstorj for platform: win32 and arch: x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN genaro-eden@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "storj"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! storj@5.0.0 preinstall: `node ./download.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the storj@5.0.0 preinstall script 'node ./download.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the storj package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs storj
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls storj
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\GenaroEden_Client\npm-debug.log

**Comment by braydonf** [comment]
Duplicate https://github.com/Storj/node-libstorj/issues/43
