### ISSUE TITLE
pkg-config error while trying to npm install -g storj

### ISSUE THREAD

**Issue by tdude08** [Storj/node-libstorj#58]
I tried to install storj globally from the getting started documentation using
```bash
npm install -g storj
````
but I get this error
'pkg-config' is not recognized as an internal or external command. 

Am I missing anything. Thanks.

System/tools details:
OS: windows 10 x64
node: v8.9.3
npm: v5.6.0

**Comment by braydonf** [comment]
Windows isn't yet supported.

Duplicate of https://github.com/Storj/node-libstorj/issues/43.

**Comment by tdude08** [comment]
Ok, thanks, I didn't know that.
