### ISSUE TITLE
AWS lambda runtime error errorMessage": "/lib64/libc.so.6: version `GLIBC_2.22' not found

### ISSUE THREAD

**Issue by suryacaprice** [Storj/node-libstorj#72]
Hi We are using the latest version of the library https://github.com/storj/node-libstorj but we get 2 error while deploying

Error 1:
{
"errorMessage": "/lib64/libc.so.6: version `GLIBC_2.22' not found (required by /var/task/node_modules/storj/build/Release/storj.node)",
"errorType": "Error",
"stackTrace": [
"Object.Module._extensions..node (module.js:597:18)",
"Module.load (module.js:487:32)",
"tryModuleLoad (module.js:446:12)",
"Function.Module._load (module.js:438:3)",
"Module.require (module.js:497:17)",
"require (internal/module.js:20:19)",
"bindings (/var/task/node_modules/bindings/bindings.js:81:44)",
"Object.<anonymous> (/var/task/node_modules/storj/index.js:3:37)",
"Module._compile (module.js:570:32)"
]
}

module initialization error: Error at Object.Module._extensions..node (module.js:681:18) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at bindings (/var/task/node_modules/bindings/bindings.js:81:44) at Object.<anonymous> (/var
module initialization error: Error
at Object.Module._extensions..node (module.js:681:18)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at bindings (/var/task/node_modules/bindings/bindings.js:81:44)
at Object.<anonymous> (/var/task/node_modules/storj/index.js:3:37)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)

Storj is using some gcc lbinary and its causing all the problems during deployment .

Deployment environment :
AWS lambda
Nodejs : 8.10

**Comment by RichardLitt** [comment]
Thanks for logging, @suryacaprice. This repository is currently deprecated. Please see ongoing work in [storj/storj](https://github.com/storj/storj) on our updated v3 network, which will be able to scale much better than this node version. 

As this work is deprecated, we aren't actively supporting this code, either. I am going to close this ticket. If you have any questions, I would recommend hopping over to [the Rocketchat](https://community.storj.io/).
